#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_stb_dxt = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

env_thirdparty = env_stb_dxt.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, ["stb_dxt_implementation.cpp"])
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_stb_dxt.add_source_files(module_obj, ["image_compress_stb_dxt.cpp", "register_types.cpp"])
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
